const judoTerms = {
    ashi: 'foot, leg',
    'ashi waza': 'foot techniques',
    arashi: 'storm',

    dan: 'black belt grade',
    de: 'advanced',
    dojo: 'training room',

    eri: 'lapel, collar',

    gaeshi: 'counter',
    gake: 'hooking, propping',
    garami: 'lock',
    gari: 'reaping',
    gatame: 'hold',
    goshi: 'hip',
    guruma: 'wheel',
    gyaku: 'reverse',
    go: 'five',
    gi: 'uniform',

    ha: 'wing',
    hara: 'stomach',
    hajime: 'start',
    hadaka: 'naked',
    hane: 'springing',
    harai: 'sweeping',
    hiji: 'elbow',
    hiza: 'knee',
    hachi: 'eight',
    
    ichi: 'one',
    ippon: 'single-handed, victory in one point',

    jigoku: 'hell',
    jikan: 'referee call to stop the clock',
    jime: 'strangle',
    'jita kyoei': 'principle of mutual prosperity',
    joseki: 'place of honour, upper seat',
    juji: 'cross',
    juu: 'ten',
    judogi: 'Judo uniform',
    judoka: 'Judo practitioner',
    
    kami: 'upper',
    kata: 'single, form or pattern, shoulder, half',
    kazure: 'modified',
    kazushi: "judo principle meaning 'off-balancing an opponent'",
    keikoku: 'warning',
    keiotsuke: 'attention',
    kesa: 'scarf',
    kiai: 'to gather spirit with a shout',
    ko: 'small',
    komi: 'pulling',
    kubi: 'neck',
    kyu: 'nine, coloured belt grade',

    makikomi: 'wraparound',
    mata: 'thigh',
    mae: 'forward, front',
    maitta: 'I surrender',
    mate: 'wait',
    morote: 'two-handed',
    mune: 'chest',
    
    nage: 'throw',
    nagekomi: 'throwing repetition training',
    nami: 'normal',
    'ne waza': 'ground techniques',
    ni: 'two',

    o: 'big, full, great',
    obi: 'belt',
    okuri: 'sliding',
    otoshi: 'drop',
    osaekomi: 'pin, referee call to begin timing',

    randori: 'free sparring',
    roku: 'six',
    rei: 'bow',
    ritsurei: 'stamding bow',
    
    sankaku: 'entangled, triangle',
    san: 'three',
    seiza: 'formal kneeling posture',
    sensei: 'teacher',
    sesae: 'propping',
    sode: 'sleeve',
    soto: 'outer',
    'sore made': 'finished, time is up',
    shiho: 'four quarter',
    shiai: 'contest, tournament, sparring match',
    shido: 'instruction, light penalty',
    shinpan: 'referee',
    shisei: 'posture',
    shodan: 'promotion, black belt',
    shomen: 'front of dojo',
    sukui: 'scooping',
    sutemi: 'sacrifice',
    sumi: 'corner',
    shi: 'four',
    shichi: 'seven',
    'seiryoku-zenyo': "judo principle meaning 'good use of energy'",
    
    tatami: 'training mat',
    te: 'hand',
    tate: 'vertical',
    'tachi waza': 'standing techniques',
    tai: 'body',
    tomoe: 'circle',
    tsuri: 'lifting',
    tori: 'attacking partner',

    uchi: 'inner',
    uchikomi: 'repetition training',
    ude: 'arm',
    uki: 'floating',
    ukemi: 'breakfall',
    uke: 'receiving partner',
    ura: 'rear, back',
    utsuri: 'shift',

    waki: 'armpit',
    waza: 'technique',

    yama: 'mountain',
    yoko: 'side',
    yoshi: 'resume action, continue',
    yubi: 'finger',
    zanshin: 'awareness',
    'zempo-kaiten': 'forward (breakfall)',
    zarei: 'kneeling bow',
    zubon: 'pants',
}
